# Generated by Django 5.0.1 on 2024-06-14 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bicro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='questin_text',
            new_name='question_text',
        ),
    ]
